#!/bin/sh

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

load_rules()
{
        #load tc rules
        if [ ! -f /etc/iptables/rules.tc ]; then
                echo "Warning: skipping tc (no rules to load)"
        else
                . /etc/iptables/rules.tc
                tc_start
        fi
}

save_rules()
{
        echo "Warning: tc save not implemented."
}

flush_rules()
{
        #flush tc rules
        if [ ! -f /etc/iptables/rules.tc ]; then
                echo "Warning: skipping tc (no rules to flush)"
        else
                . /etc/iptables/rules.tc
                tc_stop
        fi
}

case "$1" in
start|restart|reload|force-reload)
        load_rules
        ;;
save)
        save_rules
        ;;
stop)
        echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
        ;;
flush)
        flush_rules
        ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit 0
