#!/bin/sh

LOG=""

BRIDGE_IF=br-bridge
WAN_IF=eth0.2
LAN_IF=eth1.1
WLAN_IF=wlan+
LO=lo

FROM_BRIDGE="-i ${BRIDGE_IF}"
FROM_WAN="${FROM_BRIDGE} -m physdev --physdev-in ${WAN_IF}"
FROM_LAN="${FROM_BRIDGE} -m physdev --physdev-in ${LAN_IF}"
FROM_WLAN="${FROM_BRIDGE} -m physdev --physdev-in ${WLAN_IF}"
FROM_LO="-i ${LO}"

TO_BRIDGE="-o ${BRIDGE_IF}"
TO_WAN="${TO_BRIDGE} -m physdev --physdev-out ${WAN_IF}"
TO_LAN="${TO_BRIDGE} -m physdev --physdev-out ${LAN_IF}"
TO_WLAN="${TO_BRIDGE} -m physdev --physdev-out ${WLAN_IF}"
TO_LO="-o ${LO}"

FROM_WAN_TO_LAN="${FROM_WAN} ${TO_LAN}"
FROM_WAN_TO_WLAN="${FROM_WAN} ${TO_WLAN}"

FROM_LAN_TO_WAN="${FROM_LAN} ${TO_WAN}"
FROM_LAN_TO_LAN="${FROM_LAN} ${TO_LAN}"
FROM_LAN_TO_WLAN="${FROM_LAN} ${TO_WLAN}"

FROM_WLAN_TO_WAN="${FROM_WLAN} ${TO_WAN}"
FROM_WLAN_TO_LAN="${FROM_WLAN} ${TO_LAN}"
FROM_WLAN_TO_WLAN="${FROM_WLAN} ${TO_WLAN}"

ipt() {
    iptables $* 2>&1
    ip6tables $* 2>&1
}

ipt4() {
    iptables $* 2>&1
}

ipt6() {
    ip6tables $* 2>&1
}

flush_firewall() {
    ipt -t filter -F
    ipt -t filter -X
    ipt -t mangle -F
    ipt -t mangle -X
    ipt -t nat -F
    ipt -t nat -X
}

policies() {
    ipt -t filter -P INPUT ACCEPT
    ipt -t filter -P OUTPUT ACCEPT
    ipt -t filter -P FORWARD ACCEPT
}

create_chain() {
    ipt -t filter -N ${1:+"$1"}
}

chain_general_tracking() {
    create_chain general_tracking
    allow general_tracking "-m conntrack --ctstate RELATED,ESTABLISHED"
    drop general_tracking "-m conntrack --ctstate INVALID"
}

chain_icmp() {
    create_chain icmp

    allow4 icmp "-p icmp --icmp-type 0"
    allow4 icmp "-p icmp --icmp-type 3"
    allow4 icmp "-p icmp --icmp-type 8"
    allow4 icmp "-p icmp --icmp-type 11"
    reject4 icmp

    allow6 icmp "-p icmpv6 --icmpv6-type 1"
    allow6 icmp "-p icmpv6 --icmpv6-type 2"
    allow6 icmp "-p icmpv6 --icmpv6-type 3"
    allow6 icmp "-p icmpv6 --icmpv6-type 4"
    allow6 icmp "-p icmpv6 --icmpv6-type 128"
    allow6 icmp "-p icmpv6 --icmpv6-type 133"
    allow6 icmp "-p icmpv6 --icmpv6-type 134"
    allow6 icmp "-p icmpv6 --icmpv6-type 135"
    allow6 icmp "-p icmpv6 --icmpv6-type 136"
    allow6 icmp "-p icmpv6 --icmpv6-type 137"
    allow6 icmp "-p icmpv6 --icmpv6-type 141"
    allow6 icmp "-p icmpv6 --icmpv6-type 142"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 130"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 131"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 132"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 143"
    allow6 icmp "-p icmpv6 --icmpv6-type 148"
    allow6 icmp "-p icmpv6 --icmpv6-type 149"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 151"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 152"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 153"
    reject6 icmp
}

jump() {
    ipt -t filter -A ${1:+"$1"} ${3:+"$3"} ${4:+"$4"} -j ${2:+"$2"}
}

allow() {
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject() {
    [ -n "${LOG}" ] && ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "REJECT:"${1:+"$1"}":"
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop() {
    [ -n "${LOG}" ] && ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "DROP:"${1:+"$1"}":"
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

jump4() {
    ipt4 -t filter -A ${1:+"$1"} ${3:+"$3"} ${4:+"$4"} -j ${2:+"$2"}
}

allow4() {
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject4() {
    [ -n "${LOG}" ] && ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "REJECT:"${1:+"$1"}":"
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop4() {
    [ -n "${LOG}" ] && ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "DROP:"${1:+"$1"}":"
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

jump6() {
    ipt6 -t filter -A ${1:+"$1"} ${3:+"$3"} ${4:+"$4"} -j ${2:+"$2"}
}

allow6() {
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject6() {
    [ -n "${LOG}" ] && ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "REJECT:"${1:+"$1"}":"
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop6() {
    [ -n "${LOG}" ] && ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j LOG --log-prefix "DROP:"${1:+"$1"}":"
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

intercept() {
    ipt -t nat -A PREROUTING ${1:+"$1"} ${2:+"$2"} -j REDIRECT
}

firewall() {
    chain_general_tracking
    chain_icmp

    # INPUT CHAINS
    create_chain input_allow
    allow input_allow

    create_chain input_reject
    reject input_reject

    create_chain input_wan
    jump4 input_wan icmp "-p icmp"
    jump6 input_wan icmp "-p icmpv6"
    allow input_wan "-p tcp -m tcp --dport 22"
    allow4 input_wan "-p udp -m udp --dport 68"
    allow6 input_wan "-s fe80::/10 -d fe80::/10 -p udp -m udp --sport 547 --dport 546"
    jump input_wan input_reject

    # OUTPUT CHAINS
    create_chain output_allow
    allow output_allow

    create_chain output_reject
    reject output_reject

    # FORWARD CHAINS
    create_chain forward_allow
    allow forward_allow

    create_chain forward_drop
    drop forward_drop

    create_chain forward_wan_to_local
    jump4 forward_wan_to_local icmp "-p icmp"
    jump6 forward_wan_to_local icmp "-p icmpv6"
    allow4 forward_wan_to_local "-p udp -m udp --dport 68"
    allow6 forward_wan_to_local "-s fe80::/10 -d fe80::/10 -p udp -m udp --sport 547 --dport 546"
    jump forward_wan_to_local forward_drop

    # INPUT RULES
    jump INPUT general_tracking
    jump INPUT input_wan "$FROM_WAN"
    jump INPUT input_allow "$FROM_LAN"
    jump INPUT input_allow "$FROM_WLAN"
    jump INPUT input_allow "$FROM_LO"
    jump INPUT input_reject

    # OUTPUT RULES
    jump OUTPUT general_tracking
    jump OUTPUT output_allow "$TO_BRIDGE"
    jump OUTPUT output_allow "$TO_LO"
    jump OUTPUT output_reject

    # FORWARD RULES
    jump FORWARD general_tracking
    jump FORWARD forward_wan_to_local "$FROM_WAN_TO_LAN"
    jump FORWARD forward_wan_to_local "$FROM_WAN_TO_WLAN"
    jump FORWARD forward_allow "$FROM_LAN"
    jump FORWARD forward_allow "$FROM_WLAN"
    jump FORWARD forward_drop

    # INTERCEPT RULES
    intercept "$FROM_LAN" "-p udp --dport 53"
    intercept "$FROM_WLAN" "-p udp --dport 53"
}

policies
flush_firewall
firewall