#!/bin/sh

BRIDGE_IF=br-lan
WAN_IF=eth0
LAN_IF=eth1
WLAN_IF=wlan+
VPN_IF=tun+

FROM_BRIDGE="-i ${BRIDGE_IF}"
FROM_WAN="${FROM_BRIDGE} -m physdev --physdev-in ${WAN_IF}"
FROM_LAN="${FROM_BRIDGE} -m physdev --physdev-in ${LAN_IF}"
FROM_WLAN="${FROM_BRIDGE} -m physdev --physdev-in ${WLAN_IF}"
FROM_VPN="-i ${VPN_IF}"
FROM_LO="-i lo"

TO_BRIDGE="-o ${BRIDGE_IF}"
TO_WAN="${TO_BRIDGE} -m physdev --physdev-out ${WAN_IF}"
TO_LAN="${TO_BRIDGE} -m physdev --physdev-out ${LAN_IF}"
TO_WLAN="${TO_BRIDGE} -m physdev --physdev-out ${WLAN_IF}"
TO_VPN="-o ${VPN_IF}"
TO_LO="-o lo"

FROM_WAN_TO_LAN="${FROM_WAN} ${TO_LAN}"
FROM_WAN_TO_WLAN="${FROM_WAN} ${TO_WLAN}"
FROM_LAN_TO_WAN="${FROM_LAN} ${TO_WAN}"
FROM_LAN_TO_WLAN="${FROM_LAN} ${TO_WLAN}"
FROM_WLAN_TO_WAN="${FROM_WLAN} ${TO_WAN}"
FROM_WLAN_TO_LAN="${FROM_WLAN} ${TO_LAN}"

ipt() {
    iptables $* 2>&1
    ip6tables $* 2>&1
}

ipt4() {
    iptables $* 2>&1
}

ipt6() {
    ip6tables $* 2>&1
}

flush_firewall() {
    ipt -t filter -F
    ipt -t filter -X
    ipt -t mangle -F
    ipt -t mangle -X
    ipt4 -t nat -F
    ipt4 -t nat -X
}

policies() {
    ipt -t filter -P INPUT ACCEPT
    ipt -t filter -P OUTPUT ACCEPT
    ipt -t filter -P FORWARD ACCEPT
}

chain_general_tracking() {
    ipt -t filter -N general_tracking
    drop4 general_tracking "-f"
    allow general_tracking "-m conntrack --ctstate RELATED,ESTABLISHED"
    drop general_tracking "-m conntrack --ctstate INVALID"
}

chain_icmp() {
    ipt -t filter -N icmp

    allow4 icmp "-p icmp --icmp-type 0"
    allow4 icmp "-p icmp --icmp-type 3"
    allow4 icmp "-p icmp --icmp-type 8"
    allow4 icmp "-p icmp --icmp-type 11"
    drop4 icmp

    allow6 icmp "-p icmpv6 --icmpv6-type 1"
    allow6 icmp "-p icmpv6 --icmpv6-type 2"
    allow6 icmp "-p icmpv6 --icmpv6-type 3"
    allow6 icmp "-p icmpv6 --icmpv6-type 4"
    allow6 icmp "-p icmpv6 --icmpv6-type 128"
    allow6 icmp "-p icmpv6 --icmpv6-type 133"
    allow6 icmp "-p icmpv6 --icmpv6-type 134"
    allow6 icmp "-p icmpv6 --icmpv6-type 135"
    allow6 icmp "-p icmpv6 --icmpv6-type 136"
    allow6 icmp "-p icmpv6 --icmpv6-type 137"
    allow6 icmp "-p icmpv6 --icmpv6-type 141"
    allow6 icmp "-p icmpv6 --icmpv6-type 142"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 130"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 131"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 132"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 143"
    allow6 icmp "-p icmpv6 --icmpv6-type 148"
    allow6 icmp "-p icmpv6 --icmpv6-type 149"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 151"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 152"
    allow6 icmp "-s fe80::/10 -p icmpv6 --icmpv6-type 153"
    drop6 icmp
}

jump() {
    ipt -t ${1:+"$1"} -A ${2:+"$2"} ${4:+"$4"} ${5:+"$5"} -j ${3:+"$3"}
}

allow() {
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject() {
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop() {
    ipt -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

jump4() {
    ipt4 -t ${1:+"$1"} -A ${2:+"$2"} ${4:+"$4"} ${5:+"$5"} -j ${3:+"$3"}
}

allow4() {
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject4() {
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop4() {
    ipt4 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

jump6() {
    ipt6 -t ${1:+"$1"} -A ${2:+"$2"} ${4:+"$4"} ${5:+"$5"} -j ${3:+"$3"}
}

allow6() {
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j ACCEPT
}

reject6() {
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j REJECT
}

drop6() {
    ipt6 -t filter -A ${1:+"$1"} ${2:+"$2"} ${3:+"$3"} -j DROP
}

firewall() {
    # INPUT CHAINS
    ipt -t filter -N input_wan
    jump4 filter input_wan icmp "-p icmp"
    jump6 filter input_wan icmp "-p icmpv6"
    allow4 input_wan "-p udp -m udp --dport 68"
    allow6 input_wan "-s fe80::/10 -d fe80::/10 -p udp -m udp --sport 547 --dport 546"
    allow input_wan "-p tcp -m multiport --dports ssh,http,https"
    drop input_wan

    ipt -t filter -N input_lan
    allow input_lan

    ipt -t filter -N input_wlan
    allow input_wlan

    ipt -t filter -N input_vpn
    jump4 filter input_vpn icmp "-p icmp"
    jump6 filter input_vpn icmp "-p icmpv6"
    allow input_vpn "-p tcp -m multiport --dports 6881:6999"
    allow input_vpn "-p udp -m multiport --dports 6881:6999"
    drop input_vpn

    ipt -t filter -N input_lo
    allow input_lo

    # OUTPUT CHAINS
    ipt -t filter -N output_bridge
    allow output_bridge

    ipt -t filter -N output_vpn
    allow output_vpn

    ipt -t filter -N output_lo
    allow output_lo

    # FORWARD CHAINS
    ipt -t filter -N forward_wan_to_lan
    jump4 filter forward_wan_to_lan icmp "-p icmp"
    jump6 filter forward_wan_to_lan icmp "-p icmpv6"
    allow4 forward_wan_to_lan "-p udp -m udp --dport 68"
    allow6 forward_wan_to_lan "-s fe80::/10 -d fe80::/10 -p udp -m udp --sport 547 --dport 546"
    drop forward_wan_to_lan

    ipt -t filter -N forward_wan_to_wlan
    jump4 filter forward_wan_to_wlan icmp "-p icmp"
    jump6 filter forward_wan_to_wlan icmp "-p icmpv6"
    allow4 forward_wan_to_wlan "-p udp -m udp --dport 68"
    allow6 forward_wan_to_wlan "-s fe80::/10 -d fe80::/10 -p udp -m udp --sport 547 --dport 546"
    drop forward_wan_to_wlan

    ipt -t filter -N forward_lan_to_wan
    allow forward_lan_to_wan

    ipt -t filter -N forward_lan_to_wlan
    allow forward_lan_to_wlan

    ipt -t filter -N forward_wlan_to_wan
    allow forward_wlan_to_wan

    ipt -t filter -N forward_wlan_to_lan
    allow forward_wlan_to_lan

    # INPUT RULES
    jump filter INPUT general_tracking
    jump filter INPUT input_wan "$FROM_WAN"
    jump filter INPUT input_lan "$FROM_LAN"
    jump filter INPUT input_wlan "$FROM_WLAN"
    jump filter INPUT input_vpn "$FROM_VPN"
    jump filter INPUT input_lo "$FROM_LO"
    drop INPUT

    # OUTPUT RULES
    jump filter OUTPUT general_tracking
    jump filter OUTPUT output_bridge "$TO_BRIDGE"
    jump filter OUTPUT output_vpn "$TO_VPN"
    jump filter OUTPUT output_lo "$TO_LO"
    reject OUTPUT

    # FORWARD RULES
    jump filter FORWARD general_tracking
    jump filter FORWARD forward_wan_to_lan "$FROM_WAN_TO_LAN"
    jump filter FORWARD forward_wan_to_wlan "$FROM_WAN_TO_WLAN"
    jump filter FORWARD forward_lan_to_wan "$FROM_LAN_TO_WAN"
    jump filter FORWARD forward_lan_to_wlan "$FROM_LAN_TO_WLAN"
    jump filter FORWARD forward_wlan_to_wan "$FROM_WLAN_TO_WAN"
    jump filter FORWARD forward_wlan_to_lan "$FROM_WLAN_TO_LAN"
    drop FORWARD
}

policies
flush_firewall
chain_general_tracking
chain_icmp
firewall
