#!/bin/sh

IF=eno1
LINK=200000 # in kbps
TC=tc-adv
PACKET_SIZE=1514 # in bytes
BQL=$(( 1 * ${PACKET_SIZE} )) # in bytes
CAKE_OPTS="rtt 50ms besteffort dual-dsthost"

flush_qdisc() {
    $TC qdisc del dev ${IF} root 2> /dev/null
}

eth_setup() {
    # turn offloads on.
    ethtool -K ${IF} gso on 2> /dev/null
    ethtool -K ${IF} tso on 2> /dev/null
    ethtool -K ${IF} ufo on 2> /dev/null
    ethtool -K ${IF} gro on 2> /dev/null

    # setup BQL.
    if [ -e /sys/class/net/${IF}/queues/tx-0/byte_queue_limits ]
    then
        for i in /sys/class/net/${IF}/queues/tx-*/byte_queue_limits
        do
            echo ${BQL} > $i/limit_max
        done
    fi
}

egress_qdisc() {
    $TC qdisc del dev ${IF} root 2> /dev/null
    $TC qdisc add dev ${IF} root cake bandwidth ${LINK}kbit ${CAKE_OPTS}
}

tc_start() {
    flush_qdisc
    eth_setup
    egress_qdisc
}

tc_stop() {
    flush_qdisc
}

case "$1" in
start|restart|reload|force-reload)
    tc_start
    ;;
save)
    ;;
stop)
    echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
    ;;
flush)
    tc_stop
    ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit 0
