#!/bin/sh

IF=eth0.2
TC=tc
PACKET_SIZE=1514
BQL=$(( 200 * ${PACKET_SIZE} ))
ECAKE_OPTS="bandwidth 20mbit diffserv3 dual-srchost"

flush_qdisc() {
    ${TC} qdisc del dev ${IF} root &> /dev/null
}

eth_setup() {
    ethtool -K ${IF} gso on &> /dev/null
    ethtool -K ${IF} tso on &> /dev/null
    ethtool -K ${IF} ufo on &> /dev/null
    ethtool -K ${IF} gro on &> /dev/null

    if [ -e /sys/class/net/${IF}/queues/tx-0/byte_queue_limits ]
    then
        for i in /sys/class/net/${IF}/queues/tx-*/byte_queue_limits
        do
            echo ${BQL} > $i/limit_max
        done
    fi
}

egress_qdisc() {
    ${TC} qdisc del dev ${IF} root &> /dev/null
    ${TC} qdisc add dev ${IF} root cake ${ECAKE_OPTS}
}

flush_qdisc
eth_setup
egress_qdisc
